name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-run-platform-meta-environment.yaml@env-build-work-2026-09-30-224pm-no-warranty
    permissions:
      contents: write
      packages: write
      checks: write
