name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-run-platform-meta-environment.yaml@environment-and-rp-builds
    permissions:
      contents: write
      packages: write
      checks: write
